In [2]:
import numpy as np

In [3]:
# создаем матрицу А
A = np.array([
    [3, 1],
    [2, 2]
]).T

In [4]:
A

array([[3, 2],
       [1, 2]])

In [5]:
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A)
print('Собственные числа: \n', eig_values)
print('Собственные векторы: \n', eig_vectors)

Собственные числа: 
 [4. 1.]
Собственные векторы: 
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [6]:
# создаем матрицу А
A = np.array([
    [1, -5, -6],
    [4, 8, 7],
    [5, 9, 11]
]).T
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A)
print('Собственные числа: \n', eig_values)
print('Собственные векторы: \n', eig_vectors)

Собственные числа: 
 [13.59373746  5.03209301  1.37416954]
Собственные векторы: 
 [[ 0.45145779  0.83661458  0.10258363]
 [ 0.62348353  0.44632316 -0.77299039]
 [ 0.63832135  0.31760303  0.62606905]]


In [7]:
# создаем матрицу А
A = np.array([
    [1, -4, -5, -6],
    [4, 12, 8, 7],
    [5, 14, 9, 11],    [8, 15, 7, 4]
]).T
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A)
print('Собственные числа: \n', eig_values)
print('Собственные векторы: \n', eig_vectors)

Собственные числа: 
 [ 2.54687092e+01  1.53129080e+00 -1.93341868e-14 -1.00000000e+00]
Собственные векторы: 
 [[-0.33176532 -0.6739195   0.5479715  -0.5312532 ]
 [-0.75622544 -0.67703635  0.72006173 -0.64930947]
 [-0.42446012 -0.00311685 -0.00452869 -0.11805627]
 [-0.37133334  0.2957103  -0.42569687  0.5312532 ]]


In [8]:
# создаем матрицу А
A = np.array([
    [0, 1],
    [-1, 0],
]).T
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A)
print('Собственные числа: \n', eig_values)
print('Собственные векторы: \n', eig_vectors)

Собственные числа: 
 [0.+1.j 0.-1.j]
Собственные векторы: 
 [[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]


In [12]:
A = np.array([
    [1, 4, 13],
    [3, -4, 7],
    [5, 9, 12]
]).T
A

array([[ 1,  3,  5],
       [ 4, -4,  9],
       [13,  7, 12]])

In [17]:
eig_val, eig_vect = np.linalg.eig(A)
print('Собственные числа: \n', np.round(eig_val))
print('Собственные векторы: \n', np.round(eig_vect))

Собственные числа: 
 [20. -4. -7.]
Собственные векторы: 
 [[-0. -1.  0.]
 [-0.  1. -1.]
 [-1.  0.  0.]]


In [18]:
A = np.array([
    [1, 9, 4],
    [9, 4, 7],
    [4, 7, 12]
]).T

In [21]:
Gramma = A.T @ A

In [22]:
eig_val, eig_vect = np.linalg.eig(Gramma)
print('Собственные числа: \n', np.round(eig_val))
print('Собственные векторы: \n', np.round(eig_vect))

Собственные числа: 
 [391.  46.  16.]
Собственные векторы: 
 [[-0. -1. -1.]
 [-1.  1. -0.]
 [-1. -0.  1.]]


In [23]:
import numpy as np
x1 = np.array([1, 2, 1, 1]).T
x2 = np.array([70, 130, 65, 60]).T

C = np.array([[1, 0.9922], [0.9922, 1]])

eig_values, eig_vectors = np.linalg.eig(C)

x1_norm = (x1 - x1.mean()) / np.linalg.norm(x1)
x2_norm = (x2 - x2.mean()) / np.linalg.norm(x2)

x_new = x1_norm * eig_vectors[0][0] + x2_norm * eig_vectors[1][0]

x_new_norm = (x_new - x_new.mean()) / np.linalg.norm(x_new)

print(np.round(x_new_norm, 2))

## [-0.24  0.86 -0.29 -0.33]
        

[-0.24  0.86 -0.29 -0.33]
