In [8]:
import numpy as np
from sklearn.linear_model import LinearRegression

# Данные
x1 = np.array([1, 2, 3, 4, 5])
x2 = np.array([6, 7, 8, 9, 10])
y = np.array([11, 12, 13, 14, 15])

# Объединение признаков
X = np.column_stack((x1, x2))

# Обучение модели линейной регрессии
reg = LinearRegression()
reg.fit(X, y)

# Вывод вектора весов модели
weights = reg.coef_
weights


array([0.5, 0.5])

In [10]:
import numpy as np
from sklearn.linear_model import LinearRegression
x1 = np.array([1, 2, 3, 4, 5])
x2 = np.array([6, 7, 8, 9, 10])
y = np.array([11, 12, 13, 14, 15])
reg = LinearRegression()

X = np.column_stack((x1, x2))
reg.fit(X, y)
y_pred = reg.predict(np.array([[5, 6]]))
print(y_pred)

[13.]


In [12]:
from sklearn.metrics import accuracy_score, precision_score, recall_score

def calculate_metrics(y_true, y_pred):
    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred)
    recall = recall_score(y_true, y_pred)
    
    metrics = {'accuracy': accuracy, 'precision': precision, 'recall': recall}
    
    return metrics

In [16]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
X = np.random.rand(100, 5)
y = np.random.randint(0, 2, size=100)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)
f1 = round(f1_score(y_test, y_pred),2)
f1

0.52

In [21]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3, random_state=41) 
model = DecisionTreeClassifier(max_depth=3, min_samples_split=5)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.9111111111111111


In [22]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score
import numpy as np
iris = load_iris()
X = iris.data
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

forest = RandomForestClassifier()
forest.fit(X_train, y_train)
y_pred_forest = forest.predict(X_test)

grad_boost = GradientBoostingClassifier()
grad_boost.fit(X_train, y_train)
y_pred_grad_boost = grad_boost.predict(X_test)

rf_acc = accuracy_score(y_test, y_pred_forest)
gb_acc = accuracy_score(y_test, y_pred_grad_boost)

print("Accuracy случайного леса:", round(rf_acc, 2))
print("Accuracy градиентного бустинга:", round(gb_acc, 2))

Accuracy случайного леса: 1.0
Accuracy градиентного бустинга: 1.0


In [3]:
import numpy as np
from sklearn.cluster import KMeans
np.random.seed(42)
X = np.random.rand(100, 2)
model = KMeans(n_clusters=3)
model.fit_predict(X)
center_coords = model.cluster_centers_
print(center_coords)

[[0.8039633  0.57026999]
 [0.18520943 0.72228065]
 [0.36376248 0.20008043]]


/Users/nadezdaoskina/.pyenv/versions/3.10.9/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


In [4]:
import numpy as np
from sklearn.cluster import KMeans

# Генерация случайных данных
np.random.seed(42)
X = np.random.rand(100, 2)  # 100 точек в 2-мерном пространстве

# Инициализация и обучение модели k-means
model = KMeans(n_clusters=3, random_state=42)
model.fit(X)

# Получение центроидов кластеров
center_coords = model.cluster_centers_
print("Центроиды кластеров:")
print(center_coords)


Центроиды кластеров:
[[0.8039633  0.57026999]
 [0.36376248 0.20008043]
 [0.18520943 0.72228065]]


/Users/nadezdaoskina/.pyenv/versions/3.10.9/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


In [8]:
from sklearn.datasets import make_blobs
from scipy.cluster.hierarchy import linkage, fcluster
from sklearn.metrics import silhouette_score
import numpy as np

X, y = make_blobs(n_samples=100, n_features=4, centers=4, random_state=42)
silhouette_avg = []
for i in range(10):
    X, y = make_blobs(n_samples=100, n_features=4, centers=4, random_state=i)
    linkage_matrix = linkage(X, method='ward')
    labels = fcluster(linkage_matrix, t=4, criterion='maxclust')
    current_silhouette = silhouette_score(X, labels)
    silhouette_avg.append(current_silhouette)
    print(current_silhouette)

silhouette_avg = np.mean(silhouette_avg)
print(silhouette_avg)

0.7342129315790209
0.7588498590551315
0.5981066468725696
0.7529063638339899
0.8118811138698677
0.7908766199383688
0.7186103227487628
0.7561768145562359
0.6812742746955424
0.718017227342148
0.7320912174491638


In [10]:
from sklearn.datasets import make_blobs
from sklearn.cluster import DBSCAN
from sklearn.metrics import silhouette_score

X, y = make_blobs(n_samples=1000, centers=3, random_state=42)

def dbscan_silhouette(eps, min_samples):
    dbscan = DBSCAN(eps=eps, min_samples=min_samples)
    labels = dbscan.fit_predict(X)
    
    # Проверка на наличие менее чем 2 кластеров
    if len(set(labels)) <= 1:
        return -1

    return silhouette_score(X, labels)

best_eps, best_min_samples, best_silhouette = None, None, -1
for eps in [0.1, 0.5, 1]:
    for min_samples in [5, 10, 20]:
        current_silhouette = dbscan_silhouette(eps, min_samples)  # Используем уникальное имя
        if current_silhouette > best_silhouette:
            best_silhouette = current_silhouette
            best_eps = eps
            best_min_samples = min_samples
        
print([best_eps, best_min_samples, best_silhouette])


[1, 10, 0.8229345005215012]


In [16]:
import numpy as np
from sklearn.decomposition import PCA
np.random.seed(42)
# Создание искусственных данных
data = np.random.rand(1000, 10)
# Выполнение алгоритма PCA для сокращения размерности до 3-х компонент
pca = PCA(n_components=3)
pca.fit(data)
transformed_data = pca.transform(data)
# Анализ факторной нагрузки
loadings = pca.components_.T * np.sqrt(pca.explained_variance_)
# Выбор наиболее важных факторов
most_important_factors = np.argsort(np.abs(loadings[:,
0]))[::-1][:3]
# Вычисление суммы весов наиболее важных факторов
sum_weights = np.sum(np.abs(loadings[most_important_factors, 0]))
# Округление ответа до двух знаков после запятой
sum_weights_rounded = round(sum_weights, 2)
# Вывод результата
print(sum_weights_rounded)

0.47


In [19]:
import numpy as np
from scipy.linalg import svd
from sklearn.metrics import mean_squared_error
np.random.seed(42)

# Создание матрицы рейтингов
ratings = np.random.randint(1, 6, size=(5, 5))

# Разложение матрицы с помощью SVD
U, S, Vt = svd(ratings)

In [22]:
np.diag(S)

array([[17.51353895,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  4.16875468,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  2.77482398,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.78099678,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.16074933]])

In [30]:
import numpy as np

# Создаем матрицу рейтингов пользователей и товаров
R = np.array([
    [3, 1, 2, 3],
    [4, 3, 4, 3],
    [2, 2, 1, 5],
    [1, 5, 5, 2]
])

# Для примера будем считать, что нам нужно предсказать рейтинг для пользователя 2 и товара 4
user_id = 2
item_id = 4

# Ищем среднее значение рейтингов для каждого товара и вычитаем его из матрицы рейтингов
item_means = np.mean(R, axis=0)
R_norm = R - item_means

# Вычисляем сингулярное разложение матрицы рейтингов
U, s, Vt = np.linalg.svd(R_norm)

# Определяем размерность матрицы рейтингов и уменьшаем размерность сингулярным разложением
n_users, n_items = R_norm.shape
n_components = 2  # Количество главных компонент, которые мы оставляем

# Сужение размерности
U_red = U[:, :n_components]  # Берем первые n_components столбцов матрицы U
S_red = np.diag(s[:n_components])  # Создаем диагональную матрицу с первыми n_components сингулярными значениями
Vt_red = Vt[:n_components, :]  # Берем первые n_components строк из матрицы Vt

# Восстанавливаем приближенную матрицу рейтингов
R_pred = np.dot(np.dot(U_red, S_red), Vt_red) + item_means

# Округляем предсказание до одной десятой
rating_pred = round(R_pred[user_id-1, item_id-1], 1)
print(f"Предсказанный рейтинг для пользователя {user_id} и товара {item_id}: {rating_pred}")


Предсказанный рейтинг для пользователя 2 и товара 4: 2.5


In [33]:
# Создаем матрицу рейтингов пользователей и товаров
R = np.array([[3, 1, 2, 3],
[4, 3, 4, 3],
[2, 2, 1, 5],
[1, 5, 5, 2]])
# Для примера будем считать, что нам нужно предсказать рейтинг для пользователя 2 и товара 4
user_id = 2
item_id = 4
# Ищем среднее значение рейтингов для каждого товара и вычитаем его из матрицы рейтингов
item_means = np.mean(R, axis=0)
R_norm = R - item_means
# Вычисляем сингулярное разложение матрицы рейтингов
U, s, Vt = np.linalg.svd(R_norm)
# Определяем размерность матрицы рейтингов и уменьшаем размерность сингулярным разложением
n_users, n_items = R_norm.shape
n_components = 2 # Количество главных компонент, которые мы оставляем
S = np.diag(s)[:, :n_components]
U_red = U[:, :n_components]
Vt_red = Vt[:n_components, :]
R_pred = np.dot(np.dot(U_red.T, S), Vt_red) + item_means
# Округляем предсказание до одной десятой
rating_pred = round(R_pred[user_id-1, item_id-1], 1)
print(f"Предсказанный рейтинг для пользователя {user_id} и товара {item_id}: {rating_pred}")

Предсказанный рейтинг для пользователя 2 и товара 4: 3.3


In [34]:
# Создаем матрицу рейтингов пользователей и товаров
R = np.array([[3, 1, 2, 3],
[4, 3, 4, 3],
[2, 2, 1, 5],
[1, 5, 5, 2]])
# Для примера будем считать, что нам нужно предсказать рейтинг для пользователя 2 и товара 4
user_id = 2
item_id = 4
# Ищем среднее значение рейтингов для каждого товара и вычитаем его из матрицы рейтингов
item_means = np.mean(R, axis=0)
R_norm = R - item_means
# Вычисляем сингулярное разложение матрицы рейтингов
U, s, Vt = np.linalg.svd(R_norm)
# Определяем размерность матрицы рейтингов и уменьшаем размерность сингулярным разложением
n_users, n_items = R_norm.shape
n_components = 2 # Количество главных компонент, которые мы оставляем
S = np.diag(s)[:, :n_components]
U_red = U[:, :n_components]
Vt_red = Vt[:n_components, :]
R_pred = np.dot(np.dot(U_red.T, S), Vt_red) + item_means
# Округляем предсказание до одной десятой
rating_pred = round(R_pred[user_id-1, item_id-1], 1)
print(f"Предсказанный рейтинг для пользователя {user_id} и товара {item_id}: {rating_pred}")

Предсказанный рейтинг для пользователя 2 и товара 4: 3.3


In [36]:
import numpy as np

# создаем исходную матрицу A размером 5x5
A = np.array([[1, 2, 3, 4, 5], 
              [6, 7, 8, 9, 10], 
              [11, 12, 13, 14, 15], 
              [16, 17, 18, 19, 20], 
              [21, 22, 23, 24, 25]])

# создаем матрицу фильтра F размером 3x3
F = np.array([[1, 2, -1], 
              [1, 0, -1], 
              [1, 0, -1]])

# определяем размеры матриц A и F
height_a, width_a = A.shape
height_f, width_f = F.shape

# инициализируем выходную матрицу C
C = np.zeros((3,3))

# проходим по каждой строке матрицы A
for i in range(3):
    # проходим по каждому столбцу матрицы A
    for j in range(3):
        # получаем окно размером 3x3, начиная с текущей позиции
        window = A[i: i+3, j: j+3]
        # перемножаем окно с матрицей фильтра
        result = window * F
        # суммируем результаты умножения, чтобы получить новое значение в выходной матрице C
        C[i, j] = np.sum(result)

print(C)

[[-2.  0.  2.]
 [ 8. 10. 12.]
 [18. 20. 22.]]


In [37]:
# Создаем искусственные данные
import numpy as np

np.random.seed(42)

# Входные данные (матрица 100x5)
X = np.random.randn(100, 5)

# Определяем архитектуру нейронной сети
input_size = 5  # Входной размер
hidden_size = 3  # Количество нейронов в скрытом слое
output_size = 1  # Выходной размер

# Инициализируем веса случайным образом
W1 = np.random.randn(input_size, hidden_size)  # матрица весов для входного слоя
W2 = np.random.randn(hidden_size, output_size)  # матрица весов для скрытого слоя

# Определяем функцию активации (сигмоид)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Прямой проход по нейронной сети
hidden_layer = sigmoid(np.dot(X, W1))  # Расчет активаций скрытого слоя
output_layer = sigmoid(np.dot(hidden_layer, W2))  # Расчет выходного слоя

# Реальные значения (истинные метки)
y_true = np.random.randn(100, 1)

# Вычисляем среднеквадратичную ошибку
mse = np.mean((y_true - output_layer) ** 2)

# Выводим ошибку
print(f"Среднеквадратичная ошибка: {mse:.4f}")


Среднеквадратичная ошибка: 1.2729


In [40]:
# Создаем искусственные данные
import numpy as np
np.random.seed(42)

X = np.random.randn(100, 5)  # матрица 100x5

# Определяем архитектуру нейронной сети
input_size = 5
hidden_size = 3
output_size = 1

# Инициализируем веса случайным образом
W1 = np.random.randn(5, 3)  # матрица весов 5x3
W2 = np.random.randn(3, 1)  # матрица весов 3x1

# Определяем функцию активации
def sigmoid(x):

    return 1 / (1 + np.exp(-x))

# Прямой проход по нейронной сети
hidden_layer = sigmoid(np.dot(X, W1))  # скрытый слой
output_layer = np.dot(hidden_layer, W2)  # выходной слой

# Вычисляем среднеквадратичную ошибку
y_true = np.random.randn(100, 1)  # реальные значения
mse = np.round(np.mean((y_true - output_layer) ** 2),1)

print(mse)


1.1
